#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <format>

namespace job::net {

class JobIana final{
public:
    JobIana() = delete;
    ~JobIana() = delete;

    enum class IanaHeaders : uint16_t {
        AIM                                     = 0,
        Accept                                  ,
        AcceptAdditions                         ,
        AcceptCH                                ,
        AcceptDatetime                          ,
        AcceptEncoding                          ,
        AcceptFeatures                          ,
        AcceptLanguage                          ,
        AcceptPatch                             ,
        AcceptPost                              ,
        AcceptRanges                            ,
        AcceptSignature                         ,
        AccessControlAllowCredentials           ,
        AccessControlAllowHeaders               ,
        AccessControlAllowMethods               ,
        AccessControlAllowOrigin                ,
        AccessControlExposeHeaders              ,
        AccessControlMaxAge                     ,
        AccessControlRequestHeaders             ,
        AccessControlRequestMethod              ,
        Age                                     ,
        Allow                                   ,
        ALPN                                    ,
        AltSvc                                  ,
        AltUsed                                 ,
        Alternates                              ,
        ApplyToRedirectRef                      ,
        AuthenticationControl                   ,
        AuthenticationInfo                      ,
        Authorization                           ,
        CacheControl                            ,
        CacheStatus                             ,
        CalManagedID                            ,
        CalDAVTimezones                         ,
        CapsuleProtocol                         ,
        CDNCacheControl                         ,
        CDNLoop                                 ,
        CertNotAfter                            ,
        CertNotBefore                           ,
        ClearSiteData                           ,
        ClientCert                              ,
        ClientCertChain                         ,
        Close                                   ,
        Connection                              ,
        ContentDigest                           ,
        ContentDisposition                      ,
        ContentEncoding                         ,
        ContentID                               ,
        ContentLanguage                         ,
        ContentLength                           ,
        ContentLocation                         ,
        ContentRange                            ,
        ContentSecurityPolicy                   ,
        ContentSecurityPolicyReportOnly         ,
        ContentType                             ,
        Cookie                                  ,
        CrossOriginEmbedderPolicy               ,
        CrossOriginEmbedderPolicyReportOnly     ,
        CrossOriginOpenerPolicy                 ,
        CrossOriginOpenerPolicyReportOnly       ,
        CrossOriginResourcePolicy               ,
        DASL                                    ,
        Date                                    ,
        DAV                                     ,
        DeltaBase                               ,
        Depth                                   ,
        Destination                             ,
        DifferentialID                          ,
        DPoP                                    ,
        DPoPNonce                               ,
        EarlyData                               ,
        ETag                                    ,
        Expect                                  ,
        ExpectCT                                ,
        Expires                                 ,
        Forwarded                               ,
        From                                    ,
        Hobareg                                 ,
        Host                                    ,
        If                                      ,
        IfMatch                                 ,
        IfModifiedSince                         ,
        IfNoneMatch                             ,
        IfRange                                 ,
        IfScheduleTagMatch                      ,
        IfUnmodifiedSince                       ,
        IM                                      ,
        IRTokenBindingID                        ,
        KeepAlive                               ,
        Label                                   ,
        LastEventID                             ,
        LastModified                            ,
        Link                                    ,
        Location                                ,
        LockToken                               ,
        MaxForwards                             ,
        MementoDatetime                         ,
        Meter                                   ,
        MIMEVersion                             ,
        Negotiate                               ,
        NEL                                     ,
        ODataEntityId                           ,
        ODataIsolation                          ,
        ODataMaxVersion                         ,
        ODataVersion                            ,
        OptionalWWWAuth                         ,
        OrderingType                            ,
        Origin                                  ,
        OriginAgentCluster                      ,
        OSCORE                                  ,
        OSLCCoreVersion                         ,
        Overwrite                               ,
        PingFrom                                ,
        PingTo                                  ,
        Position                                ,
        Prefer                                  ,
        PreferenceApplieD                       ,
        Priority                                ,
        ProxyAuthenticate                       ,
        ProxyAuthenticationInfo                 ,
        ProxyAuthorization                      ,
        ProxyStatus                             ,
        PublicKeyPins                           ,
        PublicKeyPinsReportOnly                 ,
        Range                                   ,
        RedirectRef                             ,
        Referer                                 ,
        Refresh                                 ,
        ReplayNonce                             ,
        ReprDigest                              ,
        RetryAfter                              ,
        ScheduleReply                           ,
        ScheduleTag                             ,
        SecPurpose                              ,
        SecTokenBinding                         ,
        SecWebSocketAccept                      ,
        SecWebSocketExtensions                  ,
        SecWebSocketKey                         ,
        SecWebSocketProtocol                    ,
        SecWebSocketVersion                     ,
        Server                                  ,
        ServerTiming                            ,
        SetCookie                               ,
        Signature                               ,
        SignatureInput                          ,
        SLUG                                    ,
        SoapAction                              ,
        StatusURI                               ,
        StrictTransportSecurity                 ,
        Sunset                                  ,
        SurrogateCapability                     ,
        SurrogateControl                        ,
        TCN                                     ,
        TE                                      ,
        Timeout                                 ,
        Topic                                   ,
        Traceparent                             ,
        Tracestate                              ,
        Trailer                                 ,
        TransferEncoding                        ,
        TTL                                     ,
        Upgrade                                 ,
        Urgency                                 ,
        UserAgent                               ,
        VariantVary                             ,
        Vary                                    ,
        Via                                     ,
        WantContentDigest                       ,
        WantReprDigest                          ,
        WWWAuthenticate                         ,
        XContentTypeOptions                     ,
        XFrameOptions                           ,
        AcceptCharset                           ,
        CPEPInfo                                ,
        Pragma                                  ,
        ProtocolInfo                            ,
        ProtocolQuery
    };

    static const std::unordered_map<IanaHeaders, std::string> kIanaHeaderNames;
    static inline std::string toString(IanaHeaders header) noexcept
    {
        auto it = kIanaHeaderNames.find(header);
        if (it != kIanaHeaderNames.end())
            return it->second;
        return "Unknown-Header";
    }
    static inline bool tryFromString(const std::string &str, IanaHeaders &outHeader) noexcept
    {
        for (const auto &[key, value] : kIanaHeaderNames) {
            if (value == str) {
                outHeader = key;
                return true;
            }
        }
        return false;
    }
};
inline const std::unordered_map<JobIana::IanaHeaders, std::string> JobIana::kIanaHeaderNames = {
    { IanaHeaders::AIM                                     ,"AIM"                                       },
    { IanaHeaders::Accept                                  ,"Accept"                                    },
    { IanaHeaders::AcceptAdditions                         ,"Accept-Additions"                          },
    { IanaHeaders::AcceptCH                                ,"Accept-CH"                                 },
    { IanaHeaders::AcceptDatetime                          ,"Accept-Datetime"                           },
    { IanaHeaders::AcceptEncoding                          ,"Accept-Encoding"                           },
    { IanaHeaders::AcceptFeatures                          ,"Accept-Features"                           },
    { IanaHeaders::AcceptLanguage                          ,"Accept-Language"                           },
    { IanaHeaders::AcceptPatch                             ,"Accept-Patch"                              },
    { IanaHeaders::AcceptPost                              ,"Accept-Post"                               },
    { IanaHeaders::AcceptRanges                            ,"Accept-Ranges"                             },
    { IanaHeaders::AcceptSignature                         ,"Accept-Signature"                          },
    { IanaHeaders::AccessControlAllowCredentials           ,"Access-Control-Allow-Credentials"          },
    { IanaHeaders::AccessControlAllowHeaders               ,"Access-Control-Allow-Headers"              },
    { IanaHeaders::AccessControlAllowMethods               ,"Access-Control-Allow-Methods"              },
    { IanaHeaders::AccessControlAllowOrigin                ,"Access-Control-Allow-Origin"               },
    { IanaHeaders::AccessControlExposeHeaders              ,"Access-Control-Expose-Headers"             },
    { IanaHeaders::AccessControlMaxAge                     ,"Access-Control-Max-Age"                    },
    { IanaHeaders::AccessControlRequestHeaders             ,"Access-Control-Request-Headers"            },
    { IanaHeaders::AccessControlRequestMethod              ,"Access-Control-Request-Method"             },
    { IanaHeaders::Age                                     ,"Age"                                       },
    { IanaHeaders::Allow                                   ,"Allow"                                     },
    { IanaHeaders::ALPN                                    ,"ALPN"                                      },
    { IanaHeaders::AltSvc                                  ,"Alt-Svc"                                   },
    { IanaHeaders::AltUsed                                 ,"Alt-Used"                                  },
    { IanaHeaders::Alternates                              ,"Alternates"                                },
    { IanaHeaders::ApplyToRedirectRef                      ,"Apply-To-Redirect-Ref"                     },
    { IanaHeaders::AuthenticationControl                   ,"Authentication-Control"                    },
    { IanaHeaders::AuthenticationInfo                      ,"Authentication-Info"                       },
    { IanaHeaders::Authorization                           ,"Authorization"                             },
    { IanaHeaders::CacheControl                            ,"Cache-Control"                             },
    { IanaHeaders::CacheStatus                             ,"Cache-Status"                              },
    { IanaHeaders::CalManagedID                            ,"Cal-Managed-ID"                            },
    { IanaHeaders::CalDAVTimezones                         ,"CalDAV-Timezones"                          },
    { IanaHeaders::CapsuleProtocol                         ,"Capsule-Protocol"                          },
    { IanaHeaders::CDNCacheControl                         ,"CDN-Cache-Control"                         },
    { IanaHeaders::CDNLoop                                 ,"CDN-Loop"                                  },
    { IanaHeaders::CertNotAfter                            ,"Cert-Not-After"                            },
    { IanaHeaders::CertNotBefore                           ,"Cert-Not-Before"                           },
    { IanaHeaders::ClearSiteData                           ,"Clear-Site-Data"                           },
    { IanaHeaders::ClientCert                              ,"Client-Cert"                               },
    { IanaHeaders::ClientCertChain                         ,"Client-Cert-Chain"                         },
    { IanaHeaders::Close                                   ,"Close"                                     },
    { IanaHeaders::Connection                              ,"Connection"                                },
    { IanaHeaders::ContentDigest                           ,"Content-Digest"                            },
    { IanaHeaders::ContentDisposition                      ,"Content-Disposition"                       },
    { IanaHeaders::ContentEncoding                         ,"Content-Encoding"                          },
    { IanaHeaders::ContentID                               ,"Content-ID"                                },
    { IanaHeaders::ContentLanguage                         ,"Content-Language"                          },
    { IanaHeaders::ContentLength                           ,"Content-Length"                            },
    { IanaHeaders::ContentLocation                         ,"Content-Location"                          },
    { IanaHeaders::ContentRange                            ,"Content-Range"                             },
    { IanaHeaders::ContentSecurityPolicy                   ,"Content-Security-Policy"                   },
    { IanaHeaders::ContentSecurityPolicyReportOnly         ,"Content-Security-Policy-Report-Only"       },
    { IanaHeaders::ContentType                             ,"Content-Type"                              },
    { IanaHeaders::Cookie                                  ,"Cookie"                                    },
    { IanaHeaders::CrossOriginEmbedderPolicy               ,"Cross-Origin-Embedder-Policy"              },
    { IanaHeaders::CrossOriginEmbedderPolicyReportOnly     ,"Cross-Origin-Embedder-Policy-Report-Only"  },
    { IanaHeaders::CrossOriginOpenerPolicy                 ,"Cross-Origin-Opener-Policy"                },
    { IanaHeaders::CrossOriginOpenerPolicyReportOnly       ,"Cross-Origin-Opener-Policy-Report-Only"    },
    { IanaHeaders::CrossOriginResourcePolicy               ,"Cross-Origin-Resource-Policy"              },
    { IanaHeaders::DASL                                    ,"DASL"                                      },
    { IanaHeaders::Date                                    ,"Date"                                      },
    { IanaHeaders::DAV                                     ,"DAV"                                       },
    { IanaHeaders::DeltaBase                               ,"Delta-Base"                                },
    { IanaHeaders::Depth                                   ,"Depth"                                     },
    { IanaHeaders::Destination                             ,"Destination"                               },
    { IanaHeaders::DifferentialID                          ,"Differential-ID"                           },
    { IanaHeaders::DPoP                                    ,"DPoP"                                      },
    { IanaHeaders::DPoPNonce                               ,"DPoP-Nonce"                                },
    { IanaHeaders::EarlyData                               ,"Early-Data"                                },
    { IanaHeaders::ETag                                    ,"ETag"                                      },
    { IanaHeaders::Expect                                  ,"Expect"                                    },
    { IanaHeaders::ExpectCT                                ,"Expect-CT"                                 },
    { IanaHeaders::Expires                                 ,"Expires"                                   },
    { IanaHeaders::Forwarded                               ,"Forwarded"                                 },
    { IanaHeaders::From                                    ,"From"                                      },
    { IanaHeaders::Hobareg                                 ,"Hobareg"                                   },
    { IanaHeaders::Host                                    ,"Host"                                      },
    { IanaHeaders::If                                      ,"If"                                        },
    { IanaHeaders::IfMatch                                 ,"If-Match"                                  },
    { IanaHeaders::IfModifiedSince                         ,"If-Modified-Since"                         },
    { IanaHeaders::IfNoneMatch                             ,"If-None-Match"                             },
    { IanaHeaders::IfRange                                 ,"If-Range"                                  },
    { IanaHeaders::IfScheduleTagMatch                      ,"If-Schedule-Tag-Match"                     },
    { IanaHeaders::IfUnmodifiedSince                       ,"If-Unmodified-Since"                       },
    { IanaHeaders::IM                                      ,"IM"                                        },
    { IanaHeaders::IRTokenBindingID                        ,"IR-Token-Binding-ID"                       },
    { IanaHeaders::KeepAlive                               ,"Keep-Alive"                                },
    { IanaHeaders::Label                                   ,"Label"                                     },
    { IanaHeaders::LastEventID                             ,"Last-Event-ID"                             },
    { IanaHeaders::LastModified                            ,"Last-Modified"                             },
    { IanaHeaders::Link                                    ,"Link"                                      },
    { IanaHeaders::Location                                ,"Location"                                  },
    { IanaHeaders::LockToken                               ,"Lock-Token"                                },
    { IanaHeaders::MaxForwards                             ,"Max-Forwards"                              },
    { IanaHeaders::MementoDatetime                         ,"Memento-Datetime"                          },
    { IanaHeaders::Meter                                   ,"Meter"                                     },
    { IanaHeaders::MIMEVersion                             ,"MIME-Version"                              },
    { IanaHeaders::Negotiate                               ,"Negotiate"                                 },
    { IanaHeaders::NEL                                     ,"NEL"                                       },
    { IanaHeaders::ODataEntityId                           ,"OData-Entity-Id"                           },
    { IanaHeaders::ODataIsolation                          ,"OData-Isolation"                           },
    { IanaHeaders::ODataMaxVersion                         ,"OData-Max-Version"                         },
    { IanaHeaders::ODataVersion                            ,"OData-Version"                             },
    { IanaHeaders::OptionalWWWAuth                         ,"Optional-WWW-Auth"                         },
    { IanaHeaders::OrderingType                            ,"Ordering-Type"                             },
    { IanaHeaders::Origin                                  ,"Origin"                                    },
    { IanaHeaders::OriginAgentCluster                      ,"Origin-Agent-Cluster"                      },
    { IanaHeaders::OSCORE                                  ,"OSCORE"                                    },
    { IanaHeaders::OSLCCoreVersion                         ,"OSLC-Core-Version"                         },
    { IanaHeaders::Overwrite                               ,"Overwrite"                                 },
    { IanaHeaders::PingFrom                                ,"Ping-From"                                 },
    { IanaHeaders::PingTo                                  ,"Ping-To"                                   },
    { IanaHeaders::Position                                ,"Position"                                  },
    { IanaHeaders::Prefer                                  ,"Prefer"                                    },
    { IanaHeaders::PreferenceApplieD                       ,"Preference-Applied"                        },
    { IanaHeaders::Priority                                ,"Priority"                                  },
    { IanaHeaders::ProxyAuthenticate                       ,"Proxy-Authenticate"                        },
    { IanaHeaders::ProxyAuthenticationInfo                 ,"Proxy-Authentication-Info"                 },
    { IanaHeaders::ProxyAuthorization                      ,"Proxy-Authorization"                       },
    { IanaHeaders::ProxyStatus                             ,"Proxy-Status"                              },
    { IanaHeaders::PublicKeyPins                           ,"Public-Key-Pins"                           },
    { IanaHeaders::PublicKeyPinsReportOnly                 ,"Public-Key-Pins-Report-Only"               },
    { IanaHeaders::Range                                   ,"Range"                                     },
    { IanaHeaders::RedirectRef                             ,"Redirect-Ref"                              },
    { IanaHeaders::Referer                                 ,"Referer"                                   },
    { IanaHeaders::Refresh                                 ,"Refresh"                                   },
    { IanaHeaders::ReplayNonce                             ,"Replay-Nonce"                              },
    { IanaHeaders::ReprDigest                              ,"Repr-Digest"                               },
    { IanaHeaders::RetryAfter                              ,"Retry-After"                               },
    { IanaHeaders::ScheduleReply                           ,"Schedule-Reply"                            },
    { IanaHeaders::ScheduleTag                             ,"Schedule-Tag"                              },
    { IanaHeaders::SecPurpose                              ,"Sec-Purpose"                               },
    { IanaHeaders::SecTokenBinding                         ,"Sec-Token-Binding"                         },
    { IanaHeaders::SecWebSocketAccept                      ,"Sec-WebSocket-Accept"                      },
    { IanaHeaders::SecWebSocketExtensions                  ,"Sec-WebSocket-Extensions"                  },
    { IanaHeaders::SecWebSocketKey                         ,"Sec-WebSocket-Key"                         },
    { IanaHeaders::SecWebSocketProtocol                    ,"Sec-WebSocket-Protocol"                    },
    { IanaHeaders::SecWebSocketVersion                     ,"Sec-WebSocket-Version"                     },
    { IanaHeaders::Server                                  ,"Server"                                    },
    { IanaHeaders::ServerTiming                            ,"Server-Timing"                             },
    { IanaHeaders::SetCookie                               ,"Set-Cookie"                                },
    { IanaHeaders::Signature                               ,"Signature"                                 },
    { IanaHeaders::SignatureInput                          ,"Signature-Input"                           },
    { IanaHeaders::SLUG                                    ,"SLUG"                                      },
    { IanaHeaders::SoapAction                              ,"Soap-Action"                               },
    { IanaHeaders::StatusURI                               ,"Status-URI"                                },
    { IanaHeaders::StrictTransportSecurity                 ,"Strict-Transport-Security"                 },
    { IanaHeaders::Sunset                                  ,"Sunset"                                    },
    { IanaHeaders::SurrogateCapability                     ,"Surrogate-Capability"                      },
    { IanaHeaders::SurrogateControl                        ,"Surrogate-Control"                         },
    { IanaHeaders::TCN                                     ,"TCN"                                       },
    { IanaHeaders::TE                                      ,"TE"                                        },
    { IanaHeaders::Timeout                                 ,"Timeout"                                   },
    { IanaHeaders::Topic                                   ,"Topic"                                     },
    { IanaHeaders::Traceparent                             ,"Traceparent"                               },
    { IanaHeaders::Tracestate                              ,"Tracestate"                                },
    { IanaHeaders::Trailer                                 ,"Trailer"                                   },
    { IanaHeaders::TransferEncoding                        ,"Transfer-Encoding"                         },
    { IanaHeaders::TTL                                     ,"TTL"                                       },
    { IanaHeaders::Upgrade                                 ,"Upgrade"                                   },
    { IanaHeaders::Urgency                                 ,"Urgency"                                   },
    { IanaHeaders::UserAgent                               ,"User-Agent"                                },
    { IanaHeaders::VariantVary                             ,"Variant-Vary"                              },
    { IanaHeaders::Vary                                    ,"Vary"                                      },
    { IanaHeaders::Via                                     ,"Via"                                       },
    { IanaHeaders::WantContentDigest                       ,"Want-Content-Digest"                       },
    { IanaHeaders::WantReprDigest                          ,"Want-Repr-Digest"                          },
    { IanaHeaders::WWWAuthenticate                         ,"WWW-Authenticate"                          },
    { IanaHeaders::XContentTypeOptions                     ,"X-Content-Type-Options"                    },
    { IanaHeaders::XFrameOptions                           ,"X-Frame-Options"                           },
    { IanaHeaders::AcceptCharset                           ,"Accept-Charset"                            },
    { IanaHeaders::CPEPInfo                                ,"CPEP-Info"                                 },
    { IanaHeaders::Pragma                                  ,"Pragma"                                    },
    { IanaHeaders::ProtocolInfo                            ,"Protocol-Info"                             },
    { IanaHeaders::ProtocolQuery                           ,"Protocol-Query"                            }
    };
} // job::net

template <>
struct std::formatter<job::net::JobIana::IanaHeaders> : std::formatter<std::string> {
    auto format(job::net::JobIana::IanaHeaders h, auto &ctx) const {
        return std::formatter<std::string>::format(job::net::JobIana::toString(h), ctx);
    }
};
