#include "cpp_emitter.h"

#include <set>
#include <sstream>

#include "job_serializer_utils.h"

namespace job::serializer {

CppEmitter::CppEmitter()
{
    setLanguage(SerializeLanguage::LANG_CPP);
}

std::string CppEmitter::simpleType(const std::string &type)
{
    if (type == "i32")
        return "int32_t";

    if (type == "u32")
        return "uint32_t";

    if (type == "i64")
        return "int64_t";

    if (type == "u64")
        return "uint64_t";

    if (type == "str")
        return "std::string";

    if (type == "bool")
        return "bool";

    if (type == "float")
        return "float";

    if (type == "double")
        return "double";

    return type;
}

std::string CppEmitter::languageType(const Field &field)
{
    std::string ret = "void";

    switch (field.kind) {
    case FieldKind::Scalar:
        return simpleType(field.type);

    case FieldKind::Bin:
        if (field.size)
            return "std::array<uint8_t, " + std::to_string(*field.size) + ">";

        return "std::vector<uint8_t>";

    case FieldKind::Struct:
        return field.ref_sym ? *field.ref_sym : "UNKNOWN_STRUCT";

    case FieldKind::ListScalar:
        return "std::vector<" + simpleType(field.type.substr(5, field.type.size() - 6)) + ">";

    case FieldKind::ListBin:
        if (field.size)
            return "std::vector<std::array<uint8_t, " + std::to_string(*field.size) + ">>";

        return "std::vector<std::vector<uint8_t>>";

    case FieldKind::ListStruct:
        return "std::vector<" + (field.ref_sym ? *field.ref_sym : "UNKNOWN_STRUCT") + ">";
    }

    return ret;
}

std::string CppEmitter::exportMacro() const
{
    return m_exportMacro;
}

void CppEmitter::setExportMacro(const std::string &newExportMacro)
{
    m_exportMacro = newExportMacro;
}

std::string CppEmitter::exportHeader() const
{
    return m_exportHeader;
}

void CppEmitter::setExportHeader(const std::string &newExportHeader)
{
    m_exportHeader = newExportHeader;
}

std::string CppEmitter::renderDecl(const Schema &schema)
{
    std::string ret{};
    std::ostringstream ss;

    do {
        ss << "/* SPDX-License-Identifier: MIT */\n";
        ss << "/* SPDX-FileCopyrightText: 2026 Joseph Mills <josephjamesmills@gmail.com> */\n";
        ss << "/*\n * AUTOGENERATED by JOB serializer emitter — DO NOT EDIT BY HAND.\n */\n\n";

        ss << "#pragma once\n\n";
        ss << "#include <algorithm>\n";
        ss << "#include <array>\n";
        ss << "#include <cstdint>\n";
        ss << "#include <cstring>\n";
        ss << "#include <string>\n";
        ss << "#include <vector>\n\n";

        if (!m_exportHeader.empty())
            ss << "#include \"" << m_exportHeader << "\"\n";

        for (const auto &ex_inc : getIncludes())
            ss << "#include <" << ex_inc << ">\n";

        if (!m_exportHeader.empty() || !getIncludes().empty())
            ss << "\n";

        std::set<std::string> includes;

        for (const auto &f : schema.fields) {
            if ((f.kind == FieldKind::Struct || f.kind == FieldKind::ListStruct) && f.ref_include)
                includes.insert(*f.ref_include);
        }

        for (const auto &inc : includes)
            ss << "#include \"" << inc << "\"\n";

        if (!includes.empty())
            ss << "\n";

        ss << "namespace job::serializer::generated {\n\n";

        ss << "struct ";

        if (!m_exportMacro.empty())
            ss << m_exportMacro << " ";

        ss << schema.c_struct << " {\n";

        for (const auto &f : schema.fields) {
            const std::string pad = "    ";

            if (f.comment)
                ss << pad << "// " << *f.comment << "\n";

            ss << pad << languageType(f) << " " << f.name << ";\n";
        }

        ss << appendDecl(schema);
        ss << "\n\n";
        ss << "};\n\n";
        ss << "} // namespace job::serializer::generated\n";

        ret = ss.str();
    } while (0);

    return ret;
}

std::string CppEmitter::renderImply(const Schema &schema)
{
    std::string ret{};
    std::ostringstream ss;

    do {
        ss << "/* SPDX-License-Identifier: MIT */\n";
        ss << "/* SPDX-FileCopyrightText: 2026 Joseph Mills <josephjamesmills@gmail.com> */\n";
        ss << "/*\n * AUTOGENERATED by JOB msgpack emitter — DO NOT EDIT BY HAND.\n */\n\n";

        ss << "#include \"" << schema.hdr_name.string() << "\"\n\n";

        ss << "namespace job::serializer::generated {\n\n";

        ss << appendImply(schema);

        ss << "\n\n";
        ss << "} // namespace job::serializer::generated\n";

        ret = ss.str();
    } while (0);

    return ret;
}

} // namespace job::serializer