#include "cpp_emitter.h"

#include <sstream>
#include <set>

#include <job_logger.h>
#include "job_serializer_utils.h"

namespace job::serializer
{

CppEmitter::CppEmitter()
{
    setLanguage(SerializeLanguage::LANG_CPP);
}

CppEmitter::~CppEmitter()
{

}

std::string CppEmitter::simpleType(const std::string &type)
{
    if(type == "i32")
        return "int32_t";

    if(type == "u32")
        return "uint32_t";

    if(type == "i64")
        return "int64_t";

    if(type == "u64")
        return "uint64_t";

    if(type == "str")
        return "std::string";

    // the reset of the simple types(float,double, bool etc) alreadty match up with c++
    return type;


}

std::string CppEmitter::languageType(const Field &field)
{
    // should nver return this.
    std::string ret = "void";
    switch (field.kind){
    case FieldKind::Scalar:
        return simpleType(field.type);
    case FieldKind::Bin:
        if(field.size)
            return  "std::array<uint8_t, " + std::to_string(*field.size) + ">" ;
        else
            return "std::vector<uint8_t>";
    case FieldKind::Struct:
        return (field.ref_sym ? *field.ref_sym : "UNKNOWN_STRUCT");;
    case FieldKind::ListScalar:
        return "std::vector<" + simpleType(field.type.substr(5, field.type.size() - 6)) + ">";
    case FieldKind::ListBin:
        if(field.size)
             return "std::vector<std::array<uint8_t, " + std::to_string(*field.size) + ">>";
        else
            return "std::vector<std::vector<uint8_t>>";
    case FieldKind::ListStruct:
        return "std::vector<" + (field.ref_sym ? *field.ref_sym : "UNKNOWN_STRUCT") + ">";
    }
    return ret;
}

std::string CppEmitter::renderDecl( const Schema &schema)
{
    std::string ret{};
    std::ostringstream ss;
    do{
        ss << "/* SPDX-License-Identifier: MIT */\n";
        ss << "/* SPDX-FileCopyrightText: 2025 Joseph Mills <josephjamesmills@gmail.com> */\n";
        ss << "/*\n * AUTOGENERATED by JOB serializer emitter — DO NOT EDIT BY HAND.\n */\n\n";
        ss << "#pragma once\n\n";
        ss << "#include <cstdint>\n";
        ss << "#include <string>\n";
        ss << "#include <vector>\n";
        ss << "#include <array>\n\n";
        if(!getIncludes().empty())
            for (const auto &ex_inc : getIncludes())
                ss << "#include <" << ex_inc << ">\n\n";


        std::set<std::string> includes;
        for (const auto &f : schema.fields)
            if (f.kind == FieldKind::Struct || f.kind == FieldKind::ListStruct)
                if (f.ref_include){
                    includes.insert(*f.ref_include);
                }

        if (!includes.empty()){
            for (const auto &inc : includes)
                ss << "#include \"" << inc << "\"\n";
        }

        ss << "namespace job::serializer::generated {\n\n";
        ss << "struct " << schema.c_struct << " {\n";

        for (const auto &f : schema.fields){
            std::string pad = "    ";
            if(f.comment)
                ss << pad << "// " << (f.comment ? *f.comment : "") << "\n";
            ss << pad << languageType(f) << " " << f.name << ";\n";
        }

        ss << appendDecl(schema);
        ss << "\n\n";
        ss << "};\n\n} // namespace job::serializer::generated\n";

        ret = ss.str();
    } while (0);

    return ret;
}



std::string CppEmitter::renderImply(const Schema &schema)
{
    std::string ret{};
    std::ostringstream ss;
    do{
        ss << "/* SPDX-License-Identifier: MIT */\n";
        ss << "/* SPDX-FileCopyrightText: 2025 Joseph Mills <josephjamesmills@gmail.com> */\n";
        ss << "/*\n * AUTOGENERATED by JOB msgpack emitter — DO NOT EDIT BY HAND.\n */\n\n";

        // FIXME we need to make sure that this is really in the path
        ss << "#include \"" << schema.hdr_name.string() << "\"\n";
        // ss << "#include \"" << schema.out_base << ".hpp\"\n";

        ss << "namespace job::serializer::generated {\n\n";

        ss << appendImply(schema);

        ss << "\n\n";

        ss << "} // namespace job::serializer::generated\n";

        ret = ss.str();
    } while (0);

    return ret;
}



} // namespace job::serializer

