#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>

namespace job::io {

class JobIana{
public:
    JobIana() = default;
    ~JobIana() = default;

    enum class IanaHeaders : uint16_t {
        AIM                                     = 0   ,
        Accept                                  = 1   ,
        AcceptAdditions                         = 2   ,
        AcceptCH                                = 3   ,
        AcceptDatetime                          = 4   ,
        AcceptEncoding                          = 5   ,
        AcceptFeatures                          = 6   ,
        AcceptLanguage                          = 7   ,
        AcceptPatch                             = 8   ,
        AcceptPost                              = 9   ,
        AcceptRanges                            = 10  ,
        AcceptSignature                         = 11  ,
        AccessControlAllowCredentials           = 12  ,
        AccessControlAllowHeaders               = 13  ,
        AccessControlAllowMethods               = 14  ,
        AccessControlAllowOrigin                = 15  ,
        AccessControlExposeHeaders              = 16  ,
        AccessControlMaxAge                     = 17  ,
        AccessControlRequestHeaders             = 18  ,
        AccessControlRequestMethod              = 19  ,
        Age                                     = 20  ,
        Allow                                   = 21  ,
        ALPN                                    = 22  ,
        AltSvc                                  = 23  ,
        AltUsed                                 = 24  ,
        Alternates                              = 25  ,
        ApplyToRedirectRef                      = 26  ,
        AuthenticationControl                   = 27  ,
        AuthenticationInfo                      = 28  ,
        Authorization                           = 29  ,
        CacheControl                            = 30  ,
        CacheStatus                             = 31  ,
        CalManagedID                            = 32  ,
        CalDAVTimezones                         = 33  ,
        CapsuleProtocol                         = 34  ,
        CDNCacheControl                         = 35  ,
        CDNLoop                                 = 36  ,
        CertNotAfter                            = 37  ,
        CertNotBefore                           = 38  ,
        ClearSiteData                           = 39  ,
        ClientCert                              = 40  ,
        ClientCertChain                         = 41  ,
        Close                                   = 42  ,
        Connection                              = 43  ,
        ContentDigest                           = 44  ,
        ContentDisposition                      = 45  ,
        ContentEncoding                         = 46  ,
        ContentID                               = 47  ,
        ContentLanguage                         = 48  ,
        ContentLength                           = 49  ,
        ContentLocation                         = 50  ,
        ContentRange                            = 51  ,
        ContentSecurityPolicy                   = 52  ,
        ContentSecurityPolicyReportOnly         = 53  ,
        ContentType                             = 54  ,
        Cookie                                  = 55  ,
        CrossOriginEmbedderPolicy               = 56  ,
        CrossOriginEmbedderPolicyReportOnly     = 57  ,
        CrossOriginOpenerPolicy                 = 58  ,
        CrossOriginOpenerPolicyReportOnly       = 59  ,
        CrossOriginResourcePolicy               = 60  ,
        DASL                                    = 61  ,
        Date                                    = 62  ,
        DAV                                     = 63  ,
        DeltaBase                               = 64  ,
        Depth                                   = 65  ,
        Destination                             = 66  ,
        DifferentialID                          = 67  ,
        DPoP                                    = 68  ,
        DPoPNonce                               = 69  ,
        EarlyData                               = 70  ,
        ETag                                    = 71  ,
        Expect                                  = 72  ,
        ExpectCT                                = 73  ,
        Expires                                 = 74  ,
        Forwarded                               = 75  ,
        From                                    = 76  ,
        Hobareg                                 = 77  ,
        Host                                    = 78  ,
        If                                      = 79  ,
        IfMatch                                 = 80  ,
        IfModifiedSince                         = 81  ,
        IfNoneMatch                             = 82  ,
        IfRange                                 = 83  ,
        IfScheduleTagMatch                      = 84  ,
        IfUnmodifiedSince                       = 85  ,
        IM                                      = 86  ,
        IRTokenBindingID                        = 87  ,
        KeepAlive                               = 88  ,
        Label                                   = 89  ,
        LastEventID                             = 90  ,
        LastModified                            = 91  ,
        Link                                    = 92  ,
        Location                                = 93  ,
        LockToken                               = 94  ,
        MaxForwards                             = 95  ,
        MementoDatetime                         = 96  ,
        Meter                                   = 97  ,
        MIMEVersion                             = 98  ,
        Negotiate                               = 99  ,
        NEL                                     = 100 ,
        ODataEntityId                           = 101 ,
        ODataIsolation                          = 102 ,
        ODataMaxVersion                         = 103 ,
        ODataVersion                            = 104 ,
        OptionalWWWAuth                         = 105 ,
        OrderingType                            = 106 ,
        Origin                                  = 107 ,
        OriginAgentCluster                      = 108 ,
        OSCORE                                  = 109 ,
        OSLCCoreVersion                         = 110 ,
        Overwrite                               = 111 ,
        PingFrom                                = 112 ,
        PingTo                                  = 113 ,
        Position                                = 114 ,
        Prefer                                  = 115 ,
        PreferenceApplieD                       = 116 ,
        Priority                                = 117 ,
        ProxyAuthenticate                       = 118 ,
        ProxyAuthenticationInfo                 = 119 ,
        ProxyAuthorization                      = 120 ,
        ProxyStatus                             = 121 ,
        PublicKeyPins                           = 122 ,
        PublicKeyPinsReportOnly                 = 123 ,
        Range                                   = 124 ,
        RedirectRef                             = 125 ,
        Referer                                 = 126 ,
        Refresh                                 = 127 ,
        ReplayNonce                             = 128 ,
        ReprDigest                              = 129 ,
        RetryAfter                              = 130 ,
        ScheduleReply                           = 131 ,
        ScheduleTag                             = 132 ,
        SecPurpose                              = 133 ,
        SecTokenBinding                         = 134 ,
        SecWebSocketAccept                      = 135 ,
        SecWebSocketExtensions                  = 136 ,
        SecWebSocketKey                         = 137 ,
        SecWebSocketProtocol                    = 138 ,
        SecWebSocketVersion                     = 139 ,
        Server                                  = 140 ,
        ServerTiming                            = 141 ,
        SetCookie                               = 142 ,
        Signature                               = 143 ,
        SignatureInput                          = 144 ,
        SLUG                                    = 145 ,
        SoapAction                              = 146 ,
        StatusURI                               = 147 ,
        StrictTransportSecurity                 = 148 ,
        Sunset                                  = 149 ,
        SurrogateCapability                     = 150 ,
        SurrogateControl                        = 151 ,
        TCN                                     = 152 ,
        TE                                      = 153 ,
        Timeout                                 = 154 ,
        Topic                                   = 155 ,
        Traceparent                             = 156 ,
        Tracestate                              = 157 ,
        Trailer                                 = 158 ,
        TransferEncoding                        = 159 ,
        TTL                                     = 160 ,
        Upgrade                                 = 161 ,
        Urgency                                 = 162 ,
        UserAgent                               = 163 ,
        VariantVary                             = 164 ,
        Vary                                    = 165 ,
        Via                                     = 166 ,
        WantContentDigest                       = 167 ,
        WantReprDigest                          = 168 ,
        WWWAuthenticate                         = 169 ,
        XContentTypeOptions                     = 170 ,
        XFrameOptions                           = 171 ,
        AcceptCharset                           = 172 ,
        CPEPInfo                                = 173 ,
        Pragma                                  = 174 ,
        ProtocolInfo                            = 175 ,
        ProtocolQuery                           = 176
    };



    static const std::unordered_map<IanaHeaders, std::string> kIanaHeaderNames;
    static inline std::string toString(IanaHeaders header)
    {
        auto it = kIanaHeaderNames.find(header);
        if (it != kIanaHeaderNames.end())
            return it->second;
        return "Unknown-Header";
    }
    static inline bool tryFromString(const std::string &str, IanaHeaders &outHeader)
    {
        for (const auto &[key, value] : kIanaHeaderNames) {
            if (value == str) {
                outHeader = key;
                return true;
            }
        }
        return false;
    }

};
inline const std::unordered_map<JobIana::IanaHeaders, std::string> JobIana::kIanaHeaderNames = {
    { IanaHeaders::AIM                                     ,"AIM"                                       },
    { IanaHeaders::Accept                                  ,"Accept"                                    },
    { IanaHeaders::AcceptAdditions                         ,"Accept-Additions"                          },
    { IanaHeaders::AcceptCH                                ,"Accept-CH"                                 },
    { IanaHeaders::AcceptDatetime                          ,"Accept-Datetime"                           },
    { IanaHeaders::AcceptEncoding                          ,"Accept-Encoding"                           },
    { IanaHeaders::AcceptFeatures                          ,"Accept-Features"                           },
    { IanaHeaders::AcceptLanguage                          ,"Accept-Language"                           },
    { IanaHeaders::AcceptPatch                             ,"Accept-Patch"                              },
    { IanaHeaders::AcceptPost                              ,"Accept-Post"                               },
    { IanaHeaders::AcceptRanges                            ,"Accept-Ranges"                             },
    { IanaHeaders::AcceptSignature                         ,"Accept-Signature"                          },
    { IanaHeaders::AccessControlAllowCredentials           ,"Access-Control-Allow-Credentials"          },
    { IanaHeaders::AccessControlAllowHeaders               ,"Access-Control-Allow-Headers"              },
    { IanaHeaders::AccessControlAllowMethods               ,"Access-Control-Allow-Methods"              },
    { IanaHeaders::AccessControlAllowOrigin                ,"Access-Control-Allow-Origin"               },
    { IanaHeaders::AccessControlExposeHeaders              ,"Access-Control-Expose-Headers"             },
    { IanaHeaders::AccessControlMaxAge                     ,"Access-Control-Max-Age"                    },
    { IanaHeaders::AccessControlRequestHeaders             ,"Access-Control-Request-Headers"            },
    { IanaHeaders::AccessControlRequestMethod              ,"Access-Control-Request-Method"             },
    { IanaHeaders::Age                                     ,"Age"                                       },
    { IanaHeaders::Allow                                   ,"Allow"                                     },
    { IanaHeaders::ALPN                                    ,"ALPN"                                      },
    { IanaHeaders::AltSvc                                  ,"Alt-Svc"                                   },
    { IanaHeaders::AltUsed                                 ,"Alt-Used"                                  },
    { IanaHeaders::Alternates                              ,"Alternates"                                },
    { IanaHeaders::ApplyToRedirectRef                      ,"Apply-To-Redirect-Ref"                     },
    { IanaHeaders::AuthenticationControl                   ,"Authentication-Control"                    },
    { IanaHeaders::AuthenticationInfo                      ,"Authentication-Info"                       },
    { IanaHeaders::Authorization                           ,"Authorization"                             },
    { IanaHeaders::CacheControl                            ,"Cache-Control"                             },
    { IanaHeaders::CacheStatus                             ,"Cache-Status"                              },
    { IanaHeaders::CalManagedID                            ,"Cal-Managed-ID"                            },
    { IanaHeaders::CalDAVTimezones                         ,"CalDAV-Timezones"                          },
    { IanaHeaders::CapsuleProtocol                         ,"Capsule-Protocol"                          },
    { IanaHeaders::CDNCacheControl                         ,"CDN-Cache-Control"                         },
    { IanaHeaders::CDNLoop                                 ,"CDN-Loop"                                  },
    { IanaHeaders::CertNotAfter                            ,"Cert-Not-After"                            },
    { IanaHeaders::CertNotBefore                           ,"Cert-Not-Before"                           },
    { IanaHeaders::ClearSiteData                           ,"Clear-Site-Data"                           },
    { IanaHeaders::ClientCert                              ,"Client-Cert"                               },
    { IanaHeaders::ClientCertChain                         ,"Client-Cert-Chain"                         },
    { IanaHeaders::Close                                   ,"Close"                                     },
    { IanaHeaders::Connection                              ,"Connection"                                },
    { IanaHeaders::ContentDigest                           ,"Content-Digest"                            },
    { IanaHeaders::ContentDisposition                      ,"Content-Disposition"                       },
    { IanaHeaders::ContentEncoding                         ,"Content-Encoding"                          },
    { IanaHeaders::ContentID                               ,"Content-ID"                                },
    { IanaHeaders::ContentLanguage                         ,"Content-Language"                          },
    { IanaHeaders::ContentLength                           ,"Content-Length"                            },
    { IanaHeaders::ContentLocation                         ,"Content-Location"                          },
    { IanaHeaders::ContentRange                            ,"Content-Range"                             },
    { IanaHeaders::ContentSecurityPolicy                   ,"Content-Security-Policy"                   },
    { IanaHeaders::ContentSecurityPolicyReportOnly         ,"Content-Security-Policy-Report-Only"       },
    { IanaHeaders::ContentType                             ,"Content-Type"                              },
    { IanaHeaders::Cookie                                  ,"Cookie"                                    },
    { IanaHeaders::CrossOriginEmbedderPolicy               ,"Cross-Origin-Embedder-Policy"              },
    { IanaHeaders::CrossOriginEmbedderPolicyReportOnly     ,"Cross-Origin-Embedder-Policy-Report-Only"  },
    { IanaHeaders::CrossOriginOpenerPolicy                 ,"Cross-Origin-Opener-Policy"                },
    { IanaHeaders::CrossOriginOpenerPolicyReportOnly       ,"Cross-Origin-Opener-Policy-ReportOnly"     },
    { IanaHeaders::CrossOriginResourcePolicy               ,"Cross-Origin-Resource-Policy"              },
    { IanaHeaders::DASL                                    ,"DASL"                                      },
    { IanaHeaders::Date                                    ,"Date"                                      },
    { IanaHeaders::DAV                                     ,"DAV"                                       },
    { IanaHeaders::DeltaBase                               ,"Delta-Base"                                },
    { IanaHeaders::Depth                                   ,"Depth"                                     },
    { IanaHeaders::Destination                             ,"Destination"                               },
    { IanaHeaders::DifferentialID                          ,"Differential-ID"                           },
    { IanaHeaders::DPoP                                    ,"DPoP"                                      },
    { IanaHeaders::DPoPNonce                               ,"DPoP-Nonce"                                },
    { IanaHeaders::EarlyData                               ,"Early-Data"                                },
    { IanaHeaders::ETag                                    ,"ETag"                                      },
    { IanaHeaders::Expect                                  ,"Expect"                                    },
    { IanaHeaders::ExpectCT                                ,"Expect-CT"                                 },
    { IanaHeaders::Expires                                 ,"Expires"                                   },
    { IanaHeaders::Forwarded                               ,"Forwarded"                                 },
    { IanaHeaders::From                                    ,"From"                                      },
    { IanaHeaders::Hobareg                                 ,"Hobareg"                                   },
    { IanaHeaders::Host                                    ,"Host"                                      },
    { IanaHeaders::If                                      ,"If"                                        },
    { IanaHeaders::IfMatch                                 ,"If-Match"                                  },
    { IanaHeaders::IfModifiedSince                         ,"If-Modified-Since"                         },
    { IanaHeaders::IfNoneMatch                             ,"If-None-Match"                             },
    { IanaHeaders::IfRange                                 ,"If-Range"                                  },
    { IanaHeaders::IfScheduleTagMatch                      ,"If-Schedule-Tag-Match"                     },
    { IanaHeaders::IfUnmodifiedSince                       ,"If-Unmodified-Since"                       },
    { IanaHeaders::IM                                      ,"IM"                                        },
    { IanaHeaders::IRTokenBindingID                        ,"IR-Token-Binding-ID"                       },
    { IanaHeaders::KeepAlive                               ,"Keep-Alive"                                },
    { IanaHeaders::Label                                   ,"Label"                                     },
    { IanaHeaders::LastEventID                             ,"Last-Event-ID"                             },
    { IanaHeaders::LastModified                            ,"Last-Modified"                             },
    { IanaHeaders::Link                                    ,"Link"                                      },
    { IanaHeaders::Location                                ,"Location"                                  },
    { IanaHeaders::LockToken                               ,"Lock-Token"                                },
    { IanaHeaders::MaxForwards                             ,"Max-Forwards"                              },
    { IanaHeaders::MementoDatetime                         ,"Memento-Datetime"                          },
    { IanaHeaders::Meter                                   ,"Meter"                                     },
    { IanaHeaders::MIMEVersion                             ,"MIME-Version"                              },
    { IanaHeaders::Negotiate                               ,"Negotiate"                                 },
    { IanaHeaders::NEL                                     ,"NEL"                                       },
    { IanaHeaders::ODataEntityId                           ,"OData-Entity-Id"                           },
    { IanaHeaders::ODataIsolation                          ,"OData-Isolation"                           },
    { IanaHeaders::ODataMaxVersion                         ,"OData-Max-Version"                         },
    { IanaHeaders::ODataVersion                            ,"OData-Version"                             },
    { IanaHeaders::OptionalWWWAuth                         ,"Optional-WWW-Auth"                         },
    { IanaHeaders::OrderingType                            ,"Ordering-Type"                             },
    { IanaHeaders::Origin                                  ,"Origin"                                    },
    { IanaHeaders::OriginAgentCluster                      ,"Origin-Agent-Cluster"                      },
    { IanaHeaders::OSCORE                                  ,"OSCORE"                                    },
    { IanaHeaders::OSLCCoreVersion                         ,"OSLC-Core-Version"                         },
    { IanaHeaders::Overwrite                               ,"Overwrite"                                 },
    { IanaHeaders::PingFrom                                ,"Ping-From"                                 },
    { IanaHeaders::PingTo                                  ,"Ping-To"                                   },
    { IanaHeaders::Position                                ,"Position"                                  },
    { IanaHeaders::Prefer                                  ,"Prefer"                                    },
    { IanaHeaders::PreferenceApplieD                       ,"Preference-Applied"                        },
    { IanaHeaders::Priority                                ,"Priority"                                  },
    { IanaHeaders::ProxyAuthenticate                       ,"Proxy-Authenticate"                        },
    { IanaHeaders::ProxyAuthenticationInfo                 ,"Proxy-Authentication-Info"                 },
    { IanaHeaders::ProxyAuthorization                      ,"Proxy-Authorization"                       },
    { IanaHeaders::ProxyStatus                             ,"Proxy-Status"                              },
    { IanaHeaders::PublicKeyPins                           ,"Public-Key-Pins"                           },
    { IanaHeaders::PublicKeyPinsReportOnly                 ,"Public-Key-Pins-Report-Only"               },
    { IanaHeaders::Range                                   ,"Range"                                     },
    { IanaHeaders::RedirectRef                             ,"Redirect-Ref"                              },
    { IanaHeaders::Referer                                 ,"Referer"                                   },
    { IanaHeaders::Refresh                                 ,"Refresh"                                   },
    { IanaHeaders::ReplayNonce                             ,"Replay-Nonce"                              },
    { IanaHeaders::ReprDigest                              ,"Repr-Digest"                               },
    { IanaHeaders::RetryAfter                              ,"Retry-After"                               },
    { IanaHeaders::ScheduleReply                           ,"Schedule-Reply"                            },
    { IanaHeaders::ScheduleTag                             ,"Schedule-Tag"                              },
    { IanaHeaders::SecPurpose                              ,"Sec-Purpose"                               },
    { IanaHeaders::SecTokenBinding                         ,"Sec-Token-Binding"                         },
    { IanaHeaders::SecWebSocketAccept                      ,"Sec-WebSocket-Accept"                      },
    { IanaHeaders::SecWebSocketExtensions                  ,"Sec-WebSocket-Extensions"                  },
    { IanaHeaders::SecWebSocketKey                         ,"Sec-WebSocket-Key"                         },
    { IanaHeaders::SecWebSocketProtocol                    ,"Sec-WebSocket-Protocol"                    },
    { IanaHeaders::SecWebSocketVersion                     ,"Sec-WebSocket-Version"                     },
    { IanaHeaders::Server                                  ,"Server"                                    },
    { IanaHeaders::ServerTiming                            ,"Server-Timing"                             },
    { IanaHeaders::SetCookie                               ,"Set-Cookie"                                },
    { IanaHeaders::Signature                               ,"Signature"                                 },
    { IanaHeaders::SignatureInput                          ,"Signature-Input"                           },
    { IanaHeaders::SLUG                                    ,"SLUG"                                      },
    { IanaHeaders::SoapAction                              ,"Soap-Action"                               },
    { IanaHeaders::StatusURI                               ,"Status-URI"                                },
    { IanaHeaders::StrictTransportSecurity                 ,"Strict-Transport-Security"                 },
    { IanaHeaders::Sunset                                  ,"Sunset"                                    },
    { IanaHeaders::SurrogateCapability                     ,"Surrogate-Capability"                      },
    { IanaHeaders::SurrogateControl                        ,"Surrogate-Control"                         },
    { IanaHeaders::TCN                                     ,"TCN"                                       },
    { IanaHeaders::TE                                      ,"TE"                                        },
    { IanaHeaders::Timeout                                 ,"Timeout"                                   },
    { IanaHeaders::Topic                                   ,"Topic"                                     },
    { IanaHeaders::Traceparent                             ,"Traceparent"                               },
    { IanaHeaders::Tracestate                              ,"Tracestate"                                },
    { IanaHeaders::Trailer                                 ,"Trailer"                                   },
    { IanaHeaders::TransferEncoding                        ,"Transfer-Encoding"                         },
    { IanaHeaders::TTL                                     ,"TTL"                                       },
    { IanaHeaders::Upgrade                                 ,"Upgrade"                                   },
    { IanaHeaders::Urgency                                 ,"Urgency"                                   },
    { IanaHeaders::UserAgent                               ,"User-Agent"                                },
    { IanaHeaders::VariantVary                             ,"Variant-Vary"                              },
    { IanaHeaders::Vary                                    ,"Vary"                                      },
    { IanaHeaders::Via                                     ,"Via"                                       },
    { IanaHeaders::WantContentDigest                       ,"Want-Content-Digest"                       },
    { IanaHeaders::WantReprDigest                          ,"Want-Repr-Digest"                          },
    { IanaHeaders::WWWAuthenticate                         ,"WWW-Authenticate"                          },
    { IanaHeaders::XContentTypeOptions                     ,"X-Content-Type-Options"                    },
    { IanaHeaders::XFrameOptions                           ,"X-Frame-Options"                           },
    { IanaHeaders::AcceptCharset                           ,"Accept-Charset"                            },
    { IanaHeaders::CPEPInfo                                ,"CPEP-Info"                                 },
    { IanaHeaders::Pragma                                  ,"Pragma"                                    },
    { IanaHeaders::ProtocolInfo                            ,"Protocol-Info"                             },
    { IanaHeaders::ProtocolQuery                           ,"Protocol-Query"                            }
    };

}


