name: Build and Test JOB

on:
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mantle-os/josephs-odd-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DJOB_CI_BUILD=ON

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --target all -j$(nproc)

    - name: Test Job SIMD
      run: |
        cd "${{ github.workspace }}/build/tests/job_simd"
        ./test_job_simd

    - name: Test Job Core
      run: |
        cd "${{ github.workspace }}/build/tests/job_core"
        ./test_job_core

    - name: Test Job Threads
      run: |
        cd "${{ github.workspace }}/build/tests/job_threads"
        ./test_job_threads

    - name: Test Job Crypto
      run: |
        cd "${{ github.workspace }}/build/tests/job_crypto"
        ./test_job_crypto

    - name: Test Job Net
      run: |
        cd "${{ github.workspace }}/build/tests/job_net"
        ./test_job_net

    - name: Test Job IO
      run: |
        cd "${{ github.workspace }}/build/tests/job_io"
        ./test_job_io

    - name: Test Job Serializer
      run: |
        cd "${{ github.workspace }}/build/tests/job_serializer"
        ./test_job_serializer

    - name: Test Job Sound
      run: |
        cd "${{ github.workspace }}/build/tests/job_sound"
        ./test_job_sound

    - name: Test Job Science
      run: |
        cd "${{ github.workspace }}/build/tests/job_science"
        ./test_job_science

    - name: Test Job Zstd
      run: |
        cd "${{ github.workspace }}/build/tests/job_zstd"
        ./test_job_zstd

    - name: Test Job UART
      run: |
        cd "${{ github.workspace }}/build/tests/job_uart"
        ./test_job_uart

    - name: Test Job ANSI
      run: |
        cd "${{ github.workspace }}/build/tests/job_ansi"
        ./test_job_ansi

    - name: Test Job AI
      run: |
        cd "${{ github.workspace }}/build/tests/job_ai"
        ./test_job_ai

    - name: Test Job AiPkg
      run: |
        cd "${{ github.workspace }}/build/tests/job_aipkg"
        ./test_job_aipkg

    - name: Test Job Token
      run: |
        cd "${{ github.workspace }}/build/tests/job_token"
        ./test_job_token

    - name: Test Job GGML
      run: |
        cd "${{ github.workspace }}/build/tests/job_ggml"
        ./test_job_ggml
